In [0]:
import pandas as pd
train = pd.read_csv('./data/train.csv', index_col=0)

In [0]:
train

tid1    tid2                          title1_zh  \
id                                                          
0            0       1      2017养老保险又新增两项，农村老人人人可申领，你领到了吗   
3            2       3  "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港   
1            2       4  "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港   
2            2       5  "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港   
9            6       7               "用大蒜鉴别地沟油的方法,怎么鉴别地沟油   
...        ...     ...                                ...   
321185  167562  114783    萨拉赫人气爆棚!埃及总统大选未参选获百万选票 现任总统压力山大   
321182  167562  114782    萨拉赫人气爆棚!埃及总统大选未参选获百万选票 现任总统压力山大   
321184  167562  137705    萨拉赫人气爆棚!埃及总统大选未参选获百万选票 现任总统压力山大   
321186  167562   48989    萨拉赫人气爆棚!埃及总统大选未参选获百万选票 现任总统压力山大   
321188  167563   66480      萨达姆此项计划没有此国破坏的话，美国还会对伊拉克发动战争吗   

                         title2_zh  \
id                                   
0         警方辟谣“鸟巢大会每人领5万” 仍有老人坚持进京   
3        深圳GDP首超香港？深圳统计局辟谣：只是差距在缩小   
1             GDP首超香港？深圳澄清：还差一点点……   
2       去年深圳GDP首超香港？深圳统计局辟谣：还差611亿   
9          吃了30年食用油才知道，一片大蒜轻松鉴别地沟油   
...                            ...   
321185     西媒曝萨拉赫被推荐至巴萨 经纪人辟谣：并未发生   
321182            萨拉赫经纪人辟谣：与巴萨传闻不实   
321184   萨拉赫辟谣传闻：埃及非常团结，我们之间没有任何分歧   
321186     辟谣不实传闻，埃及足协主席：萨拉赫不会提前离队   
321188        萨达姆女儿辟谣：萨达姆政权二号人物没死！   

                                                title1_en  \
id                                                          
0       There are two new old-age insurance benefits f...   
3       "If you do not come to Shenzhen, sooner or lat...   
1       "If you do not come to Shenzhen, sooner or lat...   
2       "If you do not come to Shenzhen, sooner or lat...   
9       "How to discriminate oil from gutter oil by me...   
...                                                   ...   
321185  egypt 's presidential election failed to win m...   
321182  egypt 's presidential election failed to win m...   
321184  egypt 's presidential election failed to win m...   
321186  egypt 's presidential election failed to win m...   
321188  Will the United States wage war on Iraq withou...   

                                                title2_en      label  
id                                                                    
0       Police disprove "bird's nest congress each per...  unrelated  
3       Shenzhen's GDP outstrips Hong Kong? Shenzhen S...  unrelated  
1       The GDP overtopped Hong Kong? Shenzhen clarifi...  unrelated  
2       Shenzhen's GDP topped Hong Kong last year? She...  unrelated  
9       It took 30 years of cooking oil to know that o...     agreed  
...                                                   ...        ...  
321185  West Media Exposing Tallahlach has been recomm...  unrelated  
321182  Salah agent's dishonest rumour: rumour with ba...  unrelated  
321184  Rumor has it that Egypt is very united and the...  unrelated  
321186  False rumors, Egypt Football Association Chair...  unrelated  
321188  Saddam's daughter refutes rumors: no. 2 of Sad...  unrelated  

[320552 rows x 7 columns]

In [0]:
cols = ['title1_zh', 
        'title2_zh', 
        'label']
train = train.loc[:, cols]
train.head(3)

title1_zh                  title2_zh      label
id                                                                         
0       2017养老保险又新增两项，农村老人人人可申领，你领到了吗   警方辟谣“鸟巢大会每人领5万” 仍有老人坚持进京  unrelated
3   "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港  深圳GDP首超香港？深圳统计局辟谣：只是差距在缩小  unrelated
1   "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港       GDP首超香港？深圳澄清：还差一点点……  unrelated

In [0]:
text = 'I am Meng Lee, a data scientist based in Tokyo.'
#英文的word segmentation只需要用空白分隔
words = text.split(' ')
words

['I', 'am', 'Meng', 'Lee,', 'a', 'data', 'scientist', 'based', 'in', 'Tokyo.']

In [0]:
#中文的segmentation用結巴來做
import jieba.posseg as pseg

text = '我是李孟，在東京工作的數據科學家。'
words = pseg.cut(text)

In [0]:
words

<generator object cut at 0x000001FEBF48C148>

In [0]:
[word for word in words]

Building prefix dict from the default dictionary ...
Dumping model to file cache C:\Users\user10\AppData\Local\Temp\jieba.cache
Loading model cost 0.823 seconds.
Prefix dict has been built successfully.


[pair('我', 'r'),
 pair('是', 'v'),
 pair('李孟', 'nr'),
 pair('，', 'x'),
 pair('在', 'p'),
 pair('東京', 'ns'),
 pair('工作', 'vn'),
 pair('的', 'uj'),
 pair('數據', 'n'),
 pair('科學家', 'n'),
 pair('。', 'x')]

In [0]:
def jieba_tokenizer(text):
    words = pseg.cut(text)
    return ' '.join([
        word for word, flag in words if flag != 'x'])

In [0]:
#利用apply將jieba_tokenizer套用到所有新聞標題上
#AttributeError: 'float' object has no attribute 'decode'
#.astype(str)
t1 = pd.DataFrame(train['title1_zh'].astype(str))
t2 = pd.DataFrame(train['title2_zh'].astype(str))
train['title1_tokenized'] = t1['title1_zh'].apply(jieba_tokenizer)
train['title2_tokenized'] = t2['title2_zh'].apply(jieba_tokenizer)

In [0]:
train.iloc[:, [0, 3]].head()

title1_zh  \
id                                      
0       2017养老保险又新增两项，农村老人人人可申领，你领到了吗   
3   "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港   
1   "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港   
2   "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港   
9                "用大蒜鉴别地沟油的方法,怎么鉴别地沟油   

                                   title1_tokenized  
id                                                   
0          2017 养老保险 又 新增 两项 农村 老人 人人 可 申领 你 领到 了 吗  
3   你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港  
1   你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港  
2   你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港  
9                        用 大蒜 鉴别 地沟油 的 方法 怎么 鉴别 地沟油

In [0]:
train.iloc[:, [1, 4]].head()

title2_zh                      title2_tokenized
id                                                                  
0     警方辟谣“鸟巢大会每人领5万” 仍有老人坚持进京     警方 辟谣 鸟巢 大会 每人 领 5 万 仍 有 老人 坚持 进京
3    深圳GDP首超香港？深圳统计局辟谣：只是差距在缩小    深圳 GDP 首 超 香港 深圳 统计局 辟谣 只是 差距 在 缩小
1         GDP首超香港？深圳澄清：还差一点点……              GDP 首 超 香港 深圳 澄清 还 差 一点点
2   去年深圳GDP首超香港？深圳统计局辟谣：还差611亿  去年 深圳 GDP 首 超 香港 深圳 统计局 辟谣 还 差 611 亿
9      吃了30年食用油才知道，一片大蒜轻松鉴别地沟油     吃 了 30 年 食用油 才 知道 一片 大蒜 轻松 鉴别 地沟油

In [0]:
import keras
MAX_NUM_WORDS = 10000
tokenizer = keras.preprocessing.text.Tokenizer(num_words=MAX_NUM_WORDS)

Using TensorFlow backend.
C:\Users\user10\Anaconda3\envs\PythonGPU\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\user10\Anaconda3\envs\PythonGPU\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\user10\Anaconda3\envs\PythonGPU\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\user10\Anaconda3\envs\P

In [0]:
corpus_x1 = train.title1_tokenized
corpus_x2 = train.title2_tokenized
corpus = pd.concat([corpus_x1, corpus_x2])
corpus.shape

(641104,)

In [0]:
corpus

id
0                2017 养老保险 又 新增 两项 农村 老人 人人 可 申领 你 领到 了 吗
3         你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
1         你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
2         你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
9                              用 大蒜 鉴别 地沟油 的 方法 怎么 鉴别 地沟油
                               ...                       
321185                   西媒 曝 萨拉 赫 被 推荐 至 巴萨 经纪人 辟谣 并未 发生
321182                            萨拉 赫 经纪人 辟谣 与 巴萨 传闻 不 实
321184                 萨拉 赫 辟谣 传闻 埃及 非常 团结 我们 之间 没有 任何 分歧
321186                   辟谣 不 实 传闻 埃及 足协 主席 萨拉 赫 不会 提前 离队
321188                         萨达姆 女儿 辟谣 萨达姆 政权 二号 人物 没 死
Length: 641104, dtype: object

In [0]:
pd.DataFrame(corpus.iloc[:5],
             columns=['title'])

title
id                                                 
0          2017 养老保险 又 新增 两项 农村 老人 人人 可 申领 你 领到 了 吗
3   你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
1   你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
2   你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
9                        用 大蒜 鉴别 地沟油 的 方法 怎么 鉴别 地沟油

In [0]:
#呼叫 tokenizer 為我們查看所有文本，並建立一個字典（步驟 2 & 3）
tokenizer.fit_on_texts(corpus)

In [0]:
#等到 tokenizer 建好字典以後，我們可以進行上述第 4 個步驟，
#請 tokenizer利用內部生成的字典分別將我們的新聞標題 A 與 新聞 B 轉換成數字序列
x1_train = tokenizer.texts_to_sequences(corpus_x1)
x2_train = tokenizer.texts_to_sequences(corpus_x2)

In [0]:
#x1_train 為一個 Python list，裡頭包含了每一筆假新聞標題 A 對應的數字序列。
x1_train[0]

[217, 1268, 32, 1178, 5967, 25, 489, 2877, 116, 5559, 4, 1850, 2, 13]

In [0]:
tokenizer.index_word

{1: '的',
 2: '了',
 3: '是',
 4: '你',
 5: '被',
 6: '谣言',
 7: '吃',
 8: '辟谣',
 9: '这',
 10: '不',
 11: '人',
 12: '有',
 13: '吗',
 14: '都',
 15: '年',
 16: '在',
 17: '要',
 18: '能',
 19: '就',
 20: '和',
 21: '会',
 22: '还',
 23: '将',
 24: '3',
 25: '农村',
 26: '它',
 27: '网友',
 28: '岁',
 29: '一',
 30: '大',
 31: '用',
 32: '又',
 33: '个',
 34: '也',
 35: '后',
 36: '让',
 37: '天',
 38: '减肥',
 39: '5',
 40: '多',
 41: '月',
 42: '我',
 43: '这样',
 44: '2018',
 45: '中国',
 46: '与',
 47: '来',
 48: '上',
 49: '看',
 50: '知道',
 51: '1',
 52: '斤',
 53: '好',
 54: '一个',
 55: '可以',
 56: '再',
 57: '这些',
 58: '手机',
 59: '农民',
 60: '瘦',
 61: '为',
 62: '喝',
 63: '10',
 64: '万',
 65: '说',
 66: '孩子',
 67: '新',
 68: '他',
 69: '曝光',
 70: '已',
 71: '回应',
 72: '到',
 73: '这个',
 74: '食物',
 75: '教',
 76: '最',
 77: '2',
 78: '网传',
 79: '不能',
 80: '4',
 81: '却',
 82: '她',
 83: '真的',
 84: '每天',
 85: '补贴',
 86: '不用',
 87: '种',
 88: '怀孕',
 89: '中',
 90: '离婚',
 91: '微信',
 92: '做',
 93: '7',
 94: '没',
 95: '方法',
 96: '别',
 97: '小',
 98: '怎

In [0]:
#我們也可以利用 tokenizer.index_word 來將索引數字對應回本來的詞彙
for seq in x1_train[:1]:
    print([tokenizer.index_word[idx] for idx in seq])

['2017', '养老保险', '又', '新增', '两项', '农村', '老人', '人人', '可', '申领', '你', '领到', '了', '吗']


In [0]:
#發現每個序列長度都不一樣
for seq in x1_train[:10]:
    print(len(seq))

14
19
19
19
9
19
6
19
14
9


In [0]:
#最長的序列有61個詞彙
max_seq_len = max([len(seq) for seq in x1_train])
max_seq_len

61

In [0]:
#將每一個序列長度調整成一樣
#不夠的前面補0
#超過的尾巴刪掉
#一般來說 MAX_SEQUENCE_LENGTH 可以設定成最長序列的長度（此例中的 61）
#但這邊為了讓模型可以只看前 20 個詞彙就做出判斷以節省訓練時間
#我們先暫時使用 20 這個數字。
#using package pad_sequence
MAX_SEQUENCE_LENGTH = 20
x1_train = keras.preprocessing.sequence.pad_sequences(x1_train, 
                   maxlen=MAX_SEQUENCE_LENGTH)
x2_train = keras.preprocessing.sequence.pad_sequences(x2_train, 
                   maxlen=MAX_SEQUENCE_LENGTH)

In [0]:
x1_train

array([[   0,    0,    0, ..., 1850,    2,   13],
       [   0,    4,   10, ...,   23,  284, 1181],
       [   0,    4,   10, ...,   23,  284, 1181],
       ...,
       [   0,    0,    0, ..., 3955, 5467,   30],
       [   0,    0,    0, ..., 3955, 5467,   30],
       [   0,    0,    0, ...,   21,  113,   13]])

In [0]:
#assert斷言，不滿足條件時，觸發異常
#all sequence length are 20
for seq in x1_train + x2_train:
    assert len(seq) == 20
    
print("所有新聞標題的序列長度皆為 20 !")

所有新聞標題的序列長度皆為 20 !


In [0]:
train.label

id
0         unrelated
3         unrelated
1         unrelated
2         unrelated
9            agreed
            ...    
321185    unrelated
321182    unrelated
321184    unrelated
321186    unrelated
321188    unrelated
Name: label, Length: 320552, dtype: object

In [0]:
import numpy as np 

#製造一個字典，定義每一個分類對應到的索引數字
label_to_index = {
    'unrelated': 0, 
    'agreed': 1, 
    'disagreed': 2
}

# 將分類標籤對應到剛定義的數字
y_train = train.label.apply(lambda x: label_to_index[x])

In [0]:
y_train

id
0         0
3         0
1         0
2         0
9         1
         ..
321185    0
321182    0
321184    0
321186    0
321188    0
Name: label, Length: 320552, dtype: int64

In [0]:
y_train = np.asarray(y_train).astype('float32')
y_train

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [0]:
#現在每個分類的文字標籤都已經被轉成對應的數字，
#接著讓我們利用 Keras 做 One Hot Encoding
y_train = keras.utils.to_categorical(y_train)
y_train

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [0]:
from sklearn.model_selection import train_test_split

VALIDATION_RATIO = 0.1
# 小彩蛋
RANDOM_STATE = 9527

x1_train, x1_val, \
x2_train, x2_val, \
y_train, y_val = \
    train_test_split(
        x1_train, x2_train, y_train, 
        test_size=VALIDATION_RATIO, 
        random_state=RANDOM_STATE
)

In [0]:
print("Training Set")
print("-" * 10)
print(f"x1_train: {x1_train.shape}")
print(f"x2_train: {x2_train.shape}")
print(f"y_train : {y_train.shape}")

print("-" * 10)
print(f"x1_val:   {x1_val.shape}")
print(f"x2_val:   {x2_val.shape}")
print(f"y_val :   {y_val.shape}")
print("-" * 10)
print("Test Set")

Training Set
----------
x1_train: (288496, 20)
x2_train: (288496, 20)
y_train : (288496, 3)
----------
x1_val:   (32056, 20)
x2_val:   (32056, 20)
y_val :   (32056, 3)
----------
Test Set


In [0]:
list(enumerate(x1_train[:5]))

[(0,
  array([   0,    0,    0,    0,    0, 4178, 2972,    9,   80,   87,  717,
           18,  474,    4,  968,    4,  823,   14, 1436,  721])),
 (1,
  array([   0,    0,    0,    0,    0,    0,    0,    0,    0,  411,  308,
          809, 3142,   17,   90,  434,  191, 3713,    1,    2])),
 (2,
  array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
         5212,    5, 8867,  793, 1063, 3626,  642,  337, 1172])),
 (3,
  array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0, 2832,  244,  493,  393])),
 (4,
  array([   0,    0,    0,    0,    0,    0,    0,    0,  290,  143, 2523,
         2380,   46, 3120,   70,  243,  178, 2238, 3945, 1082]))]

In [0]:
for i, seq in enumerate(x1_train[:5]):
    print(f"新聞標題 {i + 1}: ")
    print(seq)
    print()

新聞標題 1: 
[   0    0    0    0    0 4178 2972    9   80   87  717   18  474    4
  968    4  823   14 1436  721]

新聞標題 2: 
[   0    0    0    0    0    0    0    0    0  411  308  809 3142   17
   90  434  191 3713    1    2]

新聞標題 3: 
[   0    0    0    0    0    0    0    0    0    0    0 5212    5 8867
  793 1063 3626  642  337 1172]

新聞標題 4: 
[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0 2832  244  493  393]

新聞標題 5: 
[   0    0    0    0    0    0    0    0  290  143 2523 2380   46 3120
   70  243  178 2238 3945 1082]



In [0]:
#用 tokenizer裡頭的字典 index_word 還原文本
#get(idx, '') -> 0 -> ''
for i, seq in enumerate(x1_train[:5]):
    print(f"新聞標題 {i + 1}: ")
    print([tokenizer.index_word.get(idx, '') for idx in seq])
    print()

新聞標題 1: 
['', '', '', '', '', '营养师', '补充', '这', '4', '种', '营养', '能', '帮', '你', '降血压', '你', '一样', '都', '不吃', '么']

新聞標題 2: 
['', '', '', '', '', '', '', '', '', '刘涛', '现场', '痛哭', '发飙', '要', '离婚', '直接', '把', '旁边', '的', '了']

新聞標題 3: 
['', '', '', '', '', '', '', '', '', '', '', 'nba', '被', '球星', '诞生', '火箭', '骑士', '同', '抢', '交易']

新聞標題 4: 
['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '海口', '飞机', '撒药治', '白蛾']

新聞標題 5: 
['', '', '', '', '', '', '', '', '网', '曝', '杜', '海涛', '与', '沈梦辰', '已', '分手', '疑似', '女方', '劈', '腿']



In [0]:
#model setting
# 基本參數設置，有幾個分類
NUM_CLASSES = 3
# 在語料庫裡有多少詞彙
MAX_NUM_WORDS = 10000
# 一個標題最長有幾個詞彙
MAX_SEQUENCE_LENGTH = 20
# 一個詞向量的維度
NUM_EMBEDDING_DIM = 256
# LSTM 輸出的向量維度
NUM_LSTM_UNITS = 128

In [0]:
# 建立孿生 LSTM 架構（Siamese LSTM）
from keras import Input
from keras.layers import Embedding, \
    LSTM, concatenate, Dense
from keras.models import Model

# 分別定義 2 個新聞標題 A & B 為模型輸入
# 兩個標題都是一個長度為 20 的數字序列
top_input = Input(
    shape=(MAX_SEQUENCE_LENGTH, ), 
    dtype='int32')
bm_input = Input(
    shape=(MAX_SEQUENCE_LENGTH, ), 
    dtype='int32')

# 詞嵌入層
# 經過詞嵌入層的轉換，兩個新聞標題都變成
# 一個詞向量的序列，而每個詞向量的維度
# 為 256
embedding_layer = Embedding(
    MAX_NUM_WORDS, NUM_EMBEDDING_DIM)
top_embedded = embedding_layer(
    top_input)
bm_embedded = embedding_layer(
    bm_input)

# LSTM 層
# 兩個新聞標題經過此層後
# 為一個 128 維度向量
shared_lstm = LSTM(NUM_LSTM_UNITS)
top_output = shared_lstm(top_embedded)
bm_output = shared_lstm(bm_embedded)

# 串接層將兩個新聞標題的結果串接單一向量
# 方便跟全連結層相連
merged = concatenate(
    [top_output, bm_output], 
    axis=-1)

# 全連接層搭配 Softmax Activation
# 可以回傳 3 個成對標題
# 屬於各類別的可能機率
dense =  Dense(
    units=NUM_CLASSES, 
    activation='softmax')
predictions = dense(merged)

# 我們的模型就是將數字序列的輸入，轉換
# 成 3 個分類的機率的所有步驟 / 層的總和
model = Model(
    inputs=[top_input, bm_input], 
    outputs=predictions)

In [0]:
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 20)           0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            (None, 20)           0                                            
__________________________________________________________________________________________________
embedding_1 (Embedding)         (None, 20, 256)      2560000     input_1[0][0]                    
                                                                 input_2[0][0]                    
__________________________________________________________________________________________________
lstm_1 (LSTM)                   (None, 128)          197120      embedding_1[0][0]          

In [0]:
#def model's loss function -> cross-entropy
model.compile(
    optimizer='rmsprop',
    loss='categorical_crossentropy',
    metrics=['accuracy'])

In [0]:
# 決定一次要放多少成對標題給模型訓練
BATCH_SIZE = 512

# 決定模型要看整個訓練資料集幾遍
NUM_EPOCHS = 100

#early stopping
from keras.callbacks import EarlyStopping, ModelCheckpoint
#vol acc -> mode = max
#loss -> mode = min
callback = EarlyStopping(monitor='val_loss', patience=5, verbose=1, mode="min")

# 實際訓練模型
history = model.fit(
    # 輸入是兩個長度為 20 的數字序列
    x=[x1_train, x2_train], 
    y=y_train,
    batch_size=BATCH_SIZE,
    epochs=NUM_EPOCHS,
    # 每個 epoch 完後計算驗證資料集
    # 上的 Loss 以及準確度
    validation_data=(
        [x1_val, x2_val], 
        y_val
    ),
    # 每個 epoch 隨機調整訓練資料集
    # 裡頭的數據以讓訓練過程更穩定
    callbacks=[callback],
    shuffle=True
)

Train on 288496 samples, validate on 32056 samples
Epoch 1/100
288496/288496 [==============================] - 34s 117us/step - loss: 0.0907 - accuracy: 0.9675 - val_loss: 0.5736 - val_accuracy: 0.8490
Epoch 2/100
288496/288496 [==============================] - 34s 117us/step - loss: 0.0880 - accuracy: 0.9691 - val_loss: 0.6008 - val_accuracy: 0.8530
Epoch 3/100
288496/288496 [==============================] - 34s 116us/step - loss: 0.0866 - accuracy: 0.9692 - val_loss: 0.5644 - val_accuracy: 0.8491
Epoch 4/100
288496/288496 [==============================] - 34s 117us/step - loss: 0.0855 - accuracy: 0.9696 - val_loss: 0.5916 - val_accuracy: 0.8509
Epoch 5/100
288496/288496 [==============================] - 34s 117us/step - loss: 0.0841 - accuracy: 0.9701 - val_loss: 0.6211 - val_accuracy: 0.8461
Epoch 6/100
288496/288496 [==============================] - 34s 116us/step - loss: 0.0828 - accuracy: 0.9705 - val_loss: 0.6054 - val_accuracy: 0.8474
Epoch 7/100
288496/288496 [==========

In [0]:
import pandas as pd
test = pd.read_csv('./data/test.csv', index_col=0)
test.head(3)

tid1    tid2                        title1_zh  \
id                                                        
321187  167562   59521  萨拉赫人气爆棚!埃及总统大选未参选获百万选票 现任总统压力山大   
321190  167564   91315              萨达姆被捕后告诫美国的一句话，发人深思   
321189  167563  167564    萨达姆此项计划没有此国破坏的话，美国还会对伊拉克发动战争吗   

                          title2_zh  \
id                                    
321187  辟谣！里昂官方否认费基尔加盟利物浦，难道是价格没谈拢？   
321190    10大最让美国人相信的荒诞谣言，如蜥蜴人掌控着美国   
321189          萨达姆被捕后告诫美国的一句话，发人深思   

                                                title1_en  \
id                                                          
321187  egypt 's presidential election failed to win m...   
321190  A message from Saddam Hussein after he was cap...   
321189  Will the United States wage war on Iraq withou...   

                                                title2_en  
id                                                         
321187  Lyon! Lyon officials have denied that Felipe F...  
321190  The Top 10 Americans believe that the Lizard M...  
321189  A message from Saddam Hussein after he was cap...

In [0]:
# 以下步驟分別對新聞標題 A、B　進行
# 文本斷詞 / Word Segmentation
t3 = pd.DataFrame(test['title1_zh'].astype(str))
t4 = pd.DataFrame(test['title2_zh'].astype(str))
test['title1_tokenized'] = t3['title1_zh'].apply(jieba_tokenizer)
test['title2_tokenized'] = t4['title2_zh'].apply(jieba_tokenizer)

# 將詞彙序列轉為索引數字的序列
x1_test = tokenizer.texts_to_sequences(test.title1_tokenized)
x2_test = tokenizer.texts_to_sequences(test.title2_tokenized)

# 為數字序列加入 zero padding
x1_test = keras.preprocessing.sequence.pad_sequences(
        x1_test, 
        maxlen=MAX_SEQUENCE_LENGTH)
x2_test = keras.preprocessing.sequence.pad_sequences(
        x2_test, 
        maxlen=MAX_SEQUENCE_LENGTH)    

# 利用已訓練的模型做預測
predictions = model.predict([x1_test, x2_test])

In [0]:
predictions[:5]

array([[9.3350196e-01, 1.3991307e-07, 6.6497929e-02],
       [9.9777251e-01, 5.6404252e-07, 2.2269208e-03],
       [9.5004278e-01, 4.9955778e-02, 1.5173633e-06],
       [9.9974674e-01, 4.0662785e-06, 2.4917306e-04],
       [9.7705609e-01, 6.1702972e-06, 2.2937717e-02]], dtype=float32)

In [0]:
index_to_label = {v: k for k, v in label_to_index.items()}
#argmax -> 回傳prediction(3個機率)中，最大的索引值，0/1/2
test['Category'] = [index_to_label[idx] for idx in np.argmax(predictions, axis=1)]

submission = test.loc[:, ['Category']].reset_index()

submission.columns = ['Id', 'Category']
submission.head()

Id   Category
0  321187  unrelated
1  321190  unrelated
2  321189  unrelated
3  321193  unrelated
4  321191  unrelated

In [0]:
index_to_label

{0: 'unrelated', 1: 'agreed', 2: 'disagreed'}

In [0]:
label_to_index.items()

dict_items([('unrelated', 0), ('agreed', 1), ('disagreed', 2)])

In [0]:
np.argmax(predictions, axis=1)

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

# BERT

In [3]:
import torch
from ipywidgets import IntProgress
from transformers import BertTokenizer
from IPython.display import clear_output

In [4]:
PRETRAINED_MODEL_NAME = 'bert-base-chinese'  # 指定繁簡中文 BERT-BASE 預訓練模型

# 取得此預訓練模型所使用的 tokenizer
tokenizer = BertTokenizer.from_pretrained(PRETRAINED_MODEL_NAME)

clear_output()
print("PyTorch 版本：", torch.__version__)

PyTorch 版本： 1.5.0


In [5]:
vocab = tokenizer.vocab
print("字典大小：", len(vocab))

字典大小： 21128


In [6]:
import random
random_tokens = random.sample(list(vocab), 10)
random_ids = [vocab[t] for t in random_tokens]

print("{0:20}{1:15}".format("token", "index"))
print("-" * 25)
for t, id in zip(random_tokens, random_ids):
    print("{0:15}{1:10}".format(t, id))

token               index          
-------------------------
##孛                 15160
糊                    5128
##冾                 14168
矛                    4757
髂                    7762
##磐                 17889
蘭                    5984
霈                    7449
考                    5440
##飄                 20654


In [7]:
indices = list(range(647, 657))
some_pairs = [(t, idx) for t, idx in vocab.items() if idx in indices]
for pair in some_pairs:
    print(pair)

('ㄅ', 647)
('ㄆ', 648)
('ㄇ', 649)
('ㄉ', 650)
('ㄋ', 651)
('ㄌ', 652)
('ㄍ', 653)
('ㄎ', 654)
('ㄏ', 655)
('ㄒ', 656)


In [8]:
#克漏字 [MASK]
text = "[CLS] 等到潮水 [MASK] 了，就知道誰沒穿褲子。"
tokens = tokenizer.tokenize(text)
ids = tokenizer.convert_tokens_to_ids(tokens)

print(text)
print(tokens, '...')
print(ids, '...')

[CLS] 等到潮水 [MASK] 了，就知道誰沒穿褲子。
['[CLS]', '等', '到', '潮', '水', '[MASK]', '了', '，', '就', '知', '道', '誰', '沒', '穿', '褲', '子', '。'] ...
[101, 5023, 1168, 4060, 3717, 103, 749, 8024, 2218, 4761, 6887, 6306, 3760, 4959, 6194, 2094, 511] ...


In [9]:
"""
這段程式碼載入已經訓練好的 masked 語言模型並對有 [MASK] 的句子做預測
"""
from transformers import BertForMaskedLM
# 除了 tokens 以外我們還需要辨別句子的 segment ids
tokens_tensor = torch.tensor([ids])  # (1, seq_len)
segments_tensors = torch.zeros_like(tokens_tensor)  # (1, seq_len)
maskedLM_model = BertForMaskedLM.from_pretrained(PRETRAINED_MODEL_NAME)
clear_output()
# 使用 masked LM 估計 [MASK] 位置所代表的實際 token 
maskedLM_model.eval()
#當我們在做evaluating的時候（不需要計算導數），
#我們可以將推斷（inference）的代碼包裹在with torch.no_grad():之中，以達到暫時不追踪網絡參數中的導數的目的，
#總之是為了減少可能存在的計算和內存消耗。
with torch.no_grad():
    outputs = maskedLM_model(tokens_tensor, segments_tensors)
    predictions = outputs[0]
    # (1, seq_len, num_hidden_units)
del maskedLM_model
# 將 [MASK] 位置的機率分佈取 top k 最有可能的 tokens 出來
masked_index = 5
k = 3
probs, indices = torch.topk(torch.softmax(predictions[0, masked_index], -1), k)
predicted_tokens = tokenizer.convert_ids_to_tokens(indices.tolist())
# 將 [MASK] 位置的機率分佈取 top k 最有可能的 tokens 出來
masked_index = 5
k = 3
probs, indices = torch.topk(torch.softmax(predictions[0, masked_index], -1), k)
predicted_tokens = tokenizer.convert_ids_to_tokens(indices.tolist())

In [10]:
# 顯示 top k 可能的字。一般我們就是取 top 1 當作預測值
print("輸入 tokens ：", tokens[:10], '...')
print('-' * 50)
for i, (t, p) in enumerate(zip(predicted_tokens, probs), 1):
    tokens[masked_index] = t
    print("Top {} ({:2}%)：{}".format(i, int(p.item() * 100), tokens[:10]), '...')

輸入 tokens ： ['[CLS]', '等', '到', '潮', '水', '[MASK]', '了', '，', '就', '知'] ...
--------------------------------------------------
Top 1 (67%)：['[CLS]', '等', '到', '潮', '水', '來', '了', '，', '就', '知'] ...
Top 2 (25%)：['[CLS]', '等', '到', '潮', '水', '濕', '了', '，', '就', '知'] ...
Top 3 ( 2%)：['[CLS]', '等', '到', '潮', '水', '過', '了', '，', '就', '知'] ...


In [11]:
import torch
from transformers import BertTokenizer
from IPython.display import clear_output
import pandas as pd

In [12]:
tokenizer = BertTokenizer.from_pretrained(PRETRAINED_MODEL_NAME)

INFO:transformers.tokenization_utils:loading file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-chinese-vocab.txt from cache at C:\Users\88696/.cache\torch\transformers\8a0c070123c1f794c42a29c6904beb7c1b8715741e235bee04aca2c7636fc83f.9b42061518a39ca00b8b52059fd2bede8daa613f8a8671500e518a8c29de8c00


In [13]:
# 簡單的數據清理，去除空白標題的 examples
df_train = pd.read_csv("./data/train.csv")
empty_title = ((df_train['title2_zh'].isnull()) \
               | (df_train['title1_zh'].isnull()) \
               | (df_train['title2_zh'] == '') \
               | (df_train['title2_zh'] == '0'))
df_train = df_train[~empty_title]

# 剔除過長的樣本以避免 BERT 無法將整個輸入序列放入記憶體不多的 GPU
MAX_LENGTH = 30
df_train = df_train[~(df_train.title1_zh.apply(lambda x : len(x)) > MAX_LENGTH)]
df_train = df_train[~(df_train.title2_zh.apply(lambda x : len(x)) > MAX_LENGTH)]

# 只用 1% 訓練數據看看 BERT 對少量標註數據有多少幫助
SAMPLE_FRAC = 0.01
df_train = df_train.sample(frac=SAMPLE_FRAC, random_state=9527)

# 去除不必要的欄位並重新命名兩標題的欄位名
df_train = df_train.reset_index()
df_train = df_train.loc[:, ['title1_zh', 'title2_zh', 'label']]
df_train.columns = ['text_a', 'text_b', 'label']

# idempotence, 將處理結果另存成 tsv 供 PyTorch 使用
df_train.to_csv("train.tsv", sep="\t", index=False)

print("訓練樣本數：", len(df_train))
df_train.head()

訓練樣本數： 2657


text_a                          text_b      label
0       苏有朋要结婚了，但网友觉得他还是和林心如比较合适  好闺蜜结婚给不婚族的秦岚扔花球，倒霉的秦岚掉水里笑哭苏有朋！  unrelated
1  爆料李小璐要成前妻了贾乃亮模仿王宝强一步到位、快刀斩乱麻！  李小璐要变前妻了？贾乃亮可能效仿王宝强当机立断，快刀斩乱麻！     agreed
2  为彩礼，母亲把女儿嫁给陌生男子，十年后再见面，母亲湿了眼眶  阿姨，不要彩礼是觉得你家穷，给你台阶下，不要以为我嫁不出去！  unrelated
3         猪油是个宝，一勺猪油等于十副药，先备起来再说  传承千百的猪油为何变得人人唯恐避之不及？揭开猪油的四大谣言！  unrelated
4                  剖析：香椿，为什么会致癌？            香椿含亚硝酸盐多吃会致癌？测完发现是谣言  disagreed

In [14]:
df_train.label.value_counts() / len(df_train)

unrelated    0.679338
agreed       0.294317
disagreed    0.026346
Name: label, dtype: float64

In [15]:
df_test = pd.read_csv("./data/test.csv")
df_test = df_test.loc[:, ["title1_zh", "title2_zh", "id"]]
df_test.columns = ["text_a", "text_b", "Id"]
df_test.to_csv("test.tsv", sep="\t", index=False)

print("預測樣本數：", len(df_test))
df_test.head()

預測樣本數： 80126


text_a                       text_b      Id
0  萨拉赫人气爆棚!埃及总统大选未参选获百万选票 现任总统压力山大  辟谣！里昂官方否认费基尔加盟利物浦，难道是价格没谈拢？  321187
1              萨达姆被捕后告诫美国的一句话，发人深思    10大最让美国人相信的荒诞谣言，如蜥蜴人掌控着美国  321190
2    萨达姆此项计划没有此国破坏的话，美国还会对伊拉克发动战争吗          萨达姆被捕后告诫美国的一句话，发人深思  321189
3              萨达姆被捕后告诫美国的一句话，发人深思  被绞刑处死的萨达姆是替身？他的此男人举动击破替身谣言！  321193
4              萨达姆被捕后告诫美国的一句话，发人深思         中国川贝枇杷膏在美国受到热捧？纯属谣言！  321191

In [16]:
"""
實作一個可以用來讀取訓練 / 測試集的 Dataset，這是你需要徹底了解的部分。
此 Dataset 每次將 tsv 裡的一筆成對句子轉換成 BERT 相容的格式，並回傳 3 個 tensors：
- tokens_tensor：兩個句子合併後的索引序列，包含 [CLS] 與 [SEP]
- segments_tensor：可以用來識別兩個句子界限的 binary tensor
- label_tensor：將分類標籤轉換成類別索引的 tensor, 如果是測試集則回傳 None
"""
from torch.utils.data import Dataset
 
    
class FakeNewsDataset(Dataset):
    # 讀取前處理後的 tsv 檔並初始化一些參數
    def __init__(self, mode, tokenizer):
        assert mode in ["train", "test"]  # 一般訓練你會需要 dev set
        self.mode = mode
        # 大數據你會需要用 iterator=True
        self.df = pd.read_csv(mode + ".tsv", sep="\t").fillna("")
        self.len = len(self.df)
        self.label_map = {'agreed': 0, 'disagreed': 1, 'unrelated': 2}
        self.tokenizer = tokenizer  # 我們將使用 BERT tokenizer
    
    # 定義回傳一筆訓練 / 測試數據的函式
    def __getitem__(self, idx):
        if self.mode == "test":
            text_a, text_b = self.df.iloc[idx, :2].values
            #test set has no label -> label_tensor = None
            label_tensor = None
        else:
            text_a, text_b, label = self.df.iloc[idx, :].values
            # 將 label 文字也轉換成索引(0/1/2)方便轉換成 tensor
            label_id = self.label_map[label]
            #create label tensor
            label_tensor = torch.tensor(label_id)
            
        # 建立第一個句子的 BERT tokens 並加入分隔符號 [SEP]
        word_pieces = ["[CLS]"]
        tokens_a = self.tokenizer.tokenize(text_a)
        # [CLS] [text a] [SEP]
        word_pieces += tokens_a + ["[SEP]"]
        len_a = len(word_pieces)
        
        # 第二個句子的 BERT tokens
        tokens_b = self.tokenizer.tokenize(text_b)
        # [CLS] [text b] [SEP]
        word_pieces += tokens_b + ["[SEP]"]
        len_b = len(word_pieces) - len_a
        
        # 將整個 token 序列轉換成索引序列
        ids = self.tokenizer.convert_tokens_to_ids(word_pieces)
        #token embeddings -> tokens tensor 
        tokens_tensor = torch.tensor(ids)
        
        # 將第一句包含 [SEP] 的 token 位置設為 0，其他為 1 表示第二句
        #64-bit integer (signed) -> ftype = torch.long
        segments_tensor = torch.tensor([0] * len_a + [1] * len_b, 
                                        dtype=torch.long)
        
        return (tokens_tensor, segments_tensor, label_tensor)
    
    def __len__(self):
        return self.len

In [17]:
# 初始化一個專門讀取訓練樣本的 Dataset，使用中文 BERT 斷詞
trainset = FakeNewsDataset("train", tokenizer=tokenizer)

In [18]:
trainset[0]

(tensor([ 101, 5722, 3300, 3301, 6206, 5310, 2042,  749, 8024,  852, 5381, 1351,
         6230, 2533,  800, 6820, 3221, 1469, 3360, 2552, 1963, 3683, 6772, 1394,
         6844,  102, 1962, 7318, 6057, 5310, 2042, 5314,  679, 2042, 3184, 4638,
         4912, 2269, 2803, 5709, 4413, 8024,  948, 7450, 4638, 4912, 2269, 2957,
         3717, 7027, 5010, 1526, 5722, 3300, 3301, 8013,  102]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor(2))

In [19]:
# 選擇第一個樣本
sample_idx = 0

# 將原始文本拿出做比較
text_a, text_b, label = trainset.df.iloc[sample_idx].values

# 利用剛剛建立的 Dataset 取出轉換後的 id tensors
tokens_tensor, segments_tensor, label_tensor = trainset[sample_idx]

# 將 tokens_tensor 還原成文本
tokens = tokenizer.convert_ids_to_tokens(tokens_tensor.tolist())
#join->將序列中的元素以指定的字符連接生成一個新的字符串
combined_text = "".join(tokens)

# 渲染前後差異，毫無反應就是個 print。可以直接看輸出結果
print(f"""[原始文本]
句子 1：{text_a}
句子 2：{text_b}
分類  ：{label}

--------------------

[Dataset 回傳的 tensors]
tokens_tensor  ：{tokens_tensor}

segments_tensor：{segments_tensor}

label_tensor   ：{label_tensor}

--------------------

[還原 tokens_tensors]
{combined_text}
""")

[原始文本]
句子 1：苏有朋要结婚了，但网友觉得他还是和林心如比较合适
句子 2：好闺蜜结婚给不婚族的秦岚扔花球，倒霉的秦岚掉水里笑哭苏有朋！
分類  ：unrelated

--------------------

[Dataset 回傳的 tensors]
tokens_tensor  ：tensor([ 101, 5722, 3300, 3301, 6206, 5310, 2042,  749, 8024,  852, 5381, 1351,
        6230, 2533,  800, 6820, 3221, 1469, 3360, 2552, 1963, 3683, 6772, 1394,
        6844,  102, 1962, 7318, 6057, 5310, 2042, 5314,  679, 2042, 3184, 4638,
        4912, 2269, 2803, 5709, 4413, 8024,  948, 7450, 4638, 4912, 2269, 2957,
        3717, 7027, 5010, 1526, 5722, 3300, 3301, 8013,  102])

segments_tensor：tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1])

label_tensor   ：2

--------------------

[還原 tokens_tensors]
[CLS]苏有朋要结婚了，但网友觉得他还是和林心如比较合适[SEP]好闺蜜结婚给不婚族的秦岚扔花球，倒霉的秦岚掉水里笑哭苏有朋！[SEP]



In [20]:
!pip install pysnooper -q

In [21]:
import pysnooper

class FakeNewsDataset(Dataset):
    # 讀取前處理後的 tsv 檔並初始化一些參數
    def __init__(self, mode, tokenizer):
        assert mode in ["train", "test"]  # 一般訓練你會需要 dev set
        self.mode = mode
        # 大數據你會需要用 iterator=True
        self.df = pd.read_csv(mode + ".tsv", sep="\t").fillna("")
        self.len = len(self.df)
        self.label_map = {'agreed': 0, 'disagreed': 1, 'unrelated': 2}
        self.tokenizer = tokenizer  # 我們將使用 BERT tokenizer
    
    #give tensors and text relationship
    @pysnooper.snoop()
    # 定義回傳一筆訓練 / 測試數據的函式
    def __getitem__(self, idx):
        if self.mode == "test":
            text_a, text_b = self.df.iloc[idx, :2].values
            #test set has no label -> label_tensor = None
            label_tensor = None
        else:
            text_a, text_b, label = self.df.iloc[idx, :].values
            # 將 label 文字也轉換成索引(0/1/2)方便轉換成 tensor
            label_id = self.label_map[label]
            #create label tensor
            label_tensor = torch.tensor(label_id)
            
        # 建立第一個句子的 BERT tokens 並加入分隔符號 [SEP]
        word_pieces = ["[CLS]"]
        tokens_a = self.tokenizer.tokenize(text_a)
        # [CLS] [text a] [SEP]
        word_pieces += tokens_a + ["[SEP]"]
        len_a = len(word_pieces)
        
        # 第二個句子的 BERT tokens
        tokens_b = self.tokenizer.tokenize(text_b)
        # [CLS] [text b] [SEP]
        word_pieces += tokens_b + ["[SEP]"]
        len_b = len(word_pieces) - len_a
        
        # 將整個 token 序列轉換成索引序列
        ids = self.tokenizer.convert_tokens_to_ids(word_pieces)
        #token embeddings -> tokens tensor 
        tokens_tensor = torch.tensor(ids)
        
        # 將第一句包含 [SEP] 的 token 位置設為 0，其他為 1 表示第二句
        #64-bit integer (signed) -> ftype = torch.long
        segments_tensor = torch.tensor([0] * len_a + [1] * len_b, 
                                        dtype=torch.long)
        
        return (tokens_tensor, segments_tensor, label_tensor)
    
    def __len__(self):
        return self.len

In [22]:
# 初始化一個專門讀取訓練樣本的 Dataset，使用中文 BERT 斷詞
trainset_ = FakeNewsDataset("train", tokenizer=tokenizer)

In [23]:
trainset_[0]

Source path:... <ipython-input-21-5b8d3b7a1f85>
Starting var:.. self = <__main__.FakeNewsDataset object at 0x00000217F81F9308>
Starting var:.. idx = 0
15:50:12.903786 call        17     def __getitem__(self, idx):
15:50:12.903786 line        18         if self.mode == "test":
15:50:12.904351 line        23             text_a, text_b, label = self.df.iloc[idx, :].values
New var:....... text_a = '苏有朋要结婚了，但网友觉得他还是和林心如比较合适'
New var:....... text_b = '好闺蜜结婚给不婚族的秦岚扔花球，倒霉的秦岚掉水里笑哭苏有朋！'
New var:....... label = 'unrelated'
15:50:12.904776 line        25             label_id = self.label_map[label]
New var:....... label_id = 2
15:50:12.905779 line        27             label_tensor = torch.tensor(label_id)
New var:....... label_tensor = tensor(2)
15:50:12.906054 line        30         word_pieces = ["[CLS]"]
New var:....... word_pieces = ['[CLS]']
15:50:12.906293 line        31         tokens_a = self.tokenizer.tokenize(text_a)
New var:....... tokens_a = ['苏', '有', '朋', '要', '结', '婚', '了', '，', '但

(tensor([ 101, 5722, 3300, 3301, 6206, 5310, 2042,  749, 8024,  852, 5381, 1351,
         6230, 2533,  800, 6820, 3221, 1469, 3360, 2552, 1963, 3683, 6772, 1394,
         6844,  102, 1962, 7318, 6057, 5310, 2042, 5314,  679, 2042, 3184, 4638,
         4912, 2269, 2803, 5709, 4413, 8024,  948, 7450, 4638, 4912, 2269, 2957,
         3717, 7027, 5010, 1526, 5722, 3300, 3301, 8013,  102]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor(2))

In [24]:
"""
實作可以一次回傳一個 mini-batch 的 DataLoader
這個 DataLoader 吃我們上面定義的 `FakeNewsDataset`，
回傳訓練 BERT 時會需要的 4 個 tensors：
- tokens_tensors  : (batch_size, max_seq_len_in_batch)
- segments_tensors: (batch_size, max_seq_len_in_batch)
- masks_tensors   : (batch_size, max_seq_len_in_batch)
- label_ids       : (batch_size)
"""

from torch.utils.data import DataLoader
from torch.nn.utils.rnn import pad_sequence

# 這個函式的輸入 `samples` 是一個 list，裡頭的每個 element 都是
# 剛剛定義的 `FakeNewsDataset` 回傳的一個樣本，每個樣本都包含 3 tensors：
# - tokens_tensor
# - segments_tensor
# - label_tensor
# 它會對前兩個 tensors 作 zero padding，並產生前面說明過的 masks_tensors
def create_mini_batch(samples):
    tokens_tensors = [s[0] for s in samples]
    segments_tensors = [s[1] for s in samples]
    
    # 測試集有 labels -> None
    #not None -> train set
    if samples[0][2] is not None:
        #Concatenates sequence of tensors along a new(default:0) dimension.
        label_ids = torch.stack([s[2] for s in samples])
    else:
        label_ids = None
    
    # zero pad 到同一序列長度(batch_first=True)
    tokens_tensors = pad_sequence(tokens_tensors, 
                                  batch_first=True)
    segments_tensors = pad_sequence(segments_tensors, 
                                    batch_first=True)
    
    # attention masks，將 tokens_tensors 裡頭不為 zero padding
    # 的位置設為 1 讓 BERT 只關注這些位置的 tokens
    masks_tensors = torch.zeros(tokens_tensors.shape, 
                                dtype=torch.long)
    masks_tensors = masks_tensors.masked_fill(
        tokens_tensors != 0, 1)
    
    return tokens_tensors, segments_tensors, masks_tensors, label_ids


# 初始化一個每次回傳 64 個訓練樣本的 DataLoader
# 利用 `collate_fn` 將 list of samples 合併成一個 mini-batch 是關鍵
BATCH_SIZE = 64
trainloader = DataLoader(trainset, batch_size=BATCH_SIZE, 
                         collate_fn=create_mini_batch)

In [44]:
trainloader2 = DataLoader(trainset, batch_size=16, 
                         collate_fn=create_mini_batch)

In [26]:
#生成跌代器(iter)的下一個項目
next(iter(trainloader))

(tensor([[ 101, 5722, 3300,  ...,    0,    0,    0],
         [ 101, 4255, 3160,  ..., 8013,  102,    0],
         [ 101,  711, 2506,  ..., 8013,  102,    0],
         ...,
         [ 101,  671, 2157,  ...,    0,    0,    0],
         [ 101, 1380,  677,  ...,    0,    0,    0],
         [ 101, 2458, 1853,  ...,    0,    0,    0]]),
 tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 1, 1, 0],
         [0, 0, 0,  ..., 1, 1, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]]),
 tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 1, 1, 0],
         [1, 1, 1,  ..., 1, 1, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]]),
 tensor([2, 0, 2, 2, 1, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2,
         2, 2, 2, 2, 0, 2, 2, 2, 2, 1, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0,
         0, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0, 2, 0

In [27]:
data = next(iter(trainloader))

tokens_tensors, segments_tensors, \
    masks_tensors, label_ids = data

print(f"""
tokens_tensors.shape   = {tokens_tensors.shape} 
{tokens_tensors}
------------------------
segments_tensors.shape = {segments_tensors.shape}
{segments_tensors}
------------------------
masks_tensors.shape    = {masks_tensors.shape}
{masks_tensors}
------------------------
label_ids.shape        = {label_ids.shape}
{label_ids}
""")


tokens_tensors.shape   = torch.Size([64, 63]) 
tensor([[ 101, 5722, 3300,  ...,    0,    0,    0],
        [ 101, 4255, 3160,  ..., 8013,  102,    0],
        [ 101,  711, 2506,  ..., 8013,  102,    0],
        ...,
        [ 101,  671, 2157,  ...,    0,    0,    0],
        [ 101, 1380,  677,  ...,    0,    0,    0],
        [ 101, 2458, 1853,  ...,    0,    0,    0]])
------------------------
segments_tensors.shape = torch.Size([64, 63])
tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 1, 1, 0],
        [0, 0, 0,  ..., 1, 1, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]])
------------------------
masks_tensors.shape    = torch.Size([64, 63])
tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 0],
        [1, 1, 1,  ..., 1, 1, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])
------------------------
label_ids.shape        

# 在 BERT 之上加入新 layer 成下游任務模型

In [28]:
# 載入一個可以做中文多分類任務的模型，n_class = 3
from transformers import BertForSequenceClassification

PRETRAINED_MODEL_NAME = 'bert-base-chinese'
NUM_LABELS = 3

model = BertForSequenceClassification.from_pretrained(
    PRETRAINED_MODEL_NAME, num_labels=NUM_LABELS)

clear_output()

# high-level 顯示此模型裡的 modules
print("""
name            module
----------------------""")
for name, module in model.named_children():
    if name == "bert":
        for n, _ in module.named_children():
            print(f"{name}:{n}")
    else:
        print("{:15} {}".format(name, module))


name            module
----------------------
bert:embeddings
bert:encoder
bert:pooler
dropout         Dropout(p=0.1, inplace=False)
classifier      Linear(in_features=768, out_features=3, bias=True)


In [29]:
#你也可以看到整個分類模型 model 預設的隱狀態維度(hidden size)為 768。
#如果你想要更改 BERT 的超參數，可以透過給一個 config dict 來設定。
#以下則是分類模型 model 預設的參數設定：
model.config

BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "directionality": "bidi",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "type_vocab_size": 2,
  "vocab_size": 21128
}

In [30]:
"""
定義一個可以針對特定 DataLoader 取得模型預測結果以及分類準確度的函式
之後也可以用來生成上傳到 Kaggle 競賽的預測結果

2019/11/22 更新：在將 `tokens`、`segments_tensors` 等 tensors
丟入模型時，強力建議指定每個 tensor 對應的參數名稱，以避免 HuggingFace
更新 repo 程式碼並改變參數順序時影響到我們的結果。
"""

def get_predictions(model, dataloader, compute_acc=False):
    predictions = None
    correct = 0
    total = 0
    
    #暫時不追踪網絡參數中的導數的目的，總之是為了減少可能存在的計算和內存消耗。  
    with torch.no_grad():
        # 遍巡整個資料集
        for data in dataloader:
            # 將所有 tensors 移到 GPU 上
            if next(model.parameters()).is_cuda:
                data = [t.to("cuda:0") for t in data if t is not None]
            
            
            # 別忘記前 3 個 tensors 分別為 tokens, segments 以及 masks
            # 且強烈建議在將這些 tensors 丟入 `model` 時指定對應的參數名稱
            tokens_tensors, segments_tensors, masks_tensors = data[:3]
            outputs = model(input_ids=tokens_tensors, 
                            token_type_ids=segments_tensors, 
                            attention_mask=masks_tensors)
            
            logits = outputs[0]
            #1->列max
            _, pred = torch.max(logits.data, 1)
            
            # 用來計算訓練集的分類準確率
            if compute_acc:
                labels = data[3]
                total += labels.size(0)
                correct += (pred == labels).sum().item()
                
            # 將當前 batch 記錄下來
            if predictions is None:
                predictions = pred
            else:
                predictions = torch.cat((predictions, pred))
    
    if compute_acc:
        acc = correct / total
        return predictions, acc
    return predictions

In [31]:
# 讓模型跑在 GPU 上並取得訓練集的分類準確率
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print("device:", device)
model = model.to(device)
_, acc = get_predictions(model, trainloader, compute_acc=True)
print("classification acc:", acc)

device: cuda:0
classification acc: 0.026345502446368085


In [32]:
get_predictions(model, trainloader, compute_acc=True)

(tensor([1, 1, 1,  ..., 1, 1, 1], device='cuda:0'), 0.026345502446368085)

In [33]:
#毫不意外，模型裡新加的線性分類器才剛剛被初始化，
#整個分類模型的表現低於 68 % 的 baseline 是非常正常的。

In [34]:
#算模型的參數量
def get_learnable_params(module):
    return [p for p in module.parameters() if p.requires_grad]

In [35]:
model_params = get_learnable_params(model)
clf_params = get_learnable_params(model.classifier)

#numel: 用來返回net網絡中的參數
print(f"""
整個分類模型的參數量：{sum(p.numel() for p in model_params)}
線性分類器的參數量：{sum(p.numel() for p in clf_params)}
""")


整個分類模型的參數量：102269955
線性分類器的參數量：2307



#  訓練該下游任務模型

In [50]:
%%time

# 訓練模式
model.train()

# 使用 Adam Optim 更新整個分類模型的參數
optimizer = torch.optim.Adam(model.parameters(), lr=1e-5)


EPOCHS = 6  # 幸運數字
for epoch in range(EPOCHS):
    
    running_loss = 0.0
    for data in trainloader:
        
        tokens_tensors, segments_tensors, \
        masks_tensors, labels = [t.to(device) for t in data]

        # 將參數梯度歸零
        optimizer.zero_grad()
        
        # forward pass
        outputs = model(input_ids=tokens_tensors, 
                        token_type_ids=segments_tensors, 
                        attention_mask=masks_tensors, 
                        labels=labels)

        loss = outputs[0]
        # backward
        loss.backward()
        optimizer.step()


        # 紀錄當前 batch loss
        running_loss += loss.item()
        
    # 計算分類準確率
    _, acc = get_predictions(model, trainloader, compute_acc=True)

    print('[epoch %d] loss: %.3f, acc: %.3f' %
          (epoch + 1, running_loss, acc))

RuntimeError: CUDA out of memory. Tried to allocate 12.00 MiB (GPU 0; 4.00 GiB total capacity; 2.98 GiB already allocated; 3.01 MiB free; 3.08 GiB reserved in total by PyTorch)

In [0]:
dict_ = {'Name': 'Runoob', 'Age': 7}
dict_.items()

dict_items([('Name', 'Runoob'), ('Age', 7)])